# Generated by Django 4.1.1 on 2022-09-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_funcionario_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('feature', models.CharField(max_length=100, verbose_name='Feature')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
                ('icone', models.CharField(choices=[('lni-rocket', 'Bootstrap 4 Based'), ('lni-laptop-phone', 'Fully Responsive'), ('lni-cog', 'HTML-CSS-SASS'), ('lni-leaf', 'Modern Design'), ('lni-layers', 'Multi-templates'), ('lni-leaf', 'Contact-Form')], max_length=20, verbose_name='Icone')),
                ('lado', models.CharField(choices=[('fadeInRight', 'Direita'), ('fadeInLeft', 'Esquerda')], max_length=20, verbose_name='Lado')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
    ]
