# Generated by Django 4.1.1 on 2022-09-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('icone', models.CharField(choices=[('lni-package', 'Caixa'), ('lni-drop', 'Gota'), ('lni-star', 'Estrela')], max_length=12, verbose_name='Icone')),
                ('preco', models.IntegerField(max_length=4, verbose_name='Preço')),
                ('plano', models.CharField(max_length=100, verbose_name='Plano')),
                ('usuario', models.IntegerField(max_length=3, verbose_name='Usuário')),
                ('armazenamento', models.IntegerField(max_length=3, verbose_name='Armazenamento')),
                ('suporte', models.TextField(max_length=200, verbose_name='Suporte')),
                ('atualizacao', models.TextField(max_length=200, verbose_name='Atualização')),
                ('destaque', models.CharField(choices=[('active-tb', 'Sim'), ('', 'Não')], max_length=20, verbose_name='Destaque?')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
    ]
