# Generated by Django 4.1.1 on 2022-09-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_plano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='usuario',
            field=models.IntegerField(verbose_name='Usuário'),
        ),
    ]
