# Generated by Django 4.1.1 on 2022-09-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_plano_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='preco',
            field=models.IntegerField(verbose_name='Preço'),
        ),
    ]
