# Generated by Django 4.1.1 on 2022-09-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_plano_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='armazenamento',
            field=models.IntegerField(verbose_name='Armazenamento'),
        ),
    ]
