# Generated by Django 4.1.1 on 2022-09-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_plano_armazenamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='destaque',
            field=models.CharField(choices=[('active-tb', 'Sim'), ('no-active-tb', 'Não')], max_length=20, verbose_name='Destaque?'),
        ),
    ]
