# Generated by Django 4.1.1 on 2022-09-16 15:26

import core.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_testemunho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testemunho',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 120, 'width': 120}}, verbose_name='Imagem'),
        ),
    ]
